### ISSUE TITLE
Having a demo to explain how to use the loader

### ISSUE THREAD

**Issue by m4dz** [freaktechnik/transifex-loader#10]
Hi!

I'll be happy to try and use this loader, but I can't figure how to use it in my project. Is it possible to have a demo / doc on how to configure webpack (if needed) and load transifex locales through the loader in the source code ?

Actually, I don't know how to require my locale, like with `require('transifex-loader!path/to/locales/en')` to load the `en.json` file definition 😕

**Comment by freaktechnik** [comment]
Hi

the configuration of the loader doesn't go via webpack but instead via the transifex config files .transifexrc and .tx/config. The options you have via webpack are described in https://github.com/freaktechnik/transifex-loader#query-options.

Your require statement looks correct, though you technically don't need '-loader', as webpack adds that for you. I am not sure if the loader would currently work if you omit the .json, I've never tried that. Note that the target file has to exist in your file system, so you need to do an initial run of `tx pull` to get all the lang files.

If that doesn't work for you, please let me know if you get an error (the loader gives errors in some cases, in others it falls back to just returning the local version of the file) and if possible your .tx/config, as I am not sure how correct my tx config parsing is - I've only tested it against my own configs.
