### ISSUE TITLE
Ability to push source file?

### ISSUE THREAD

**Issue by delphiactual** [freaktechnik/transifex-loader#30]
Does this loader also have the ability to push the source file to Transifex?

EDIT:
Workflow should push the source file, then pull all the translated files.

**Comment by freaktechnik** [comment]
No, the loader only downloads translations from transifex. Pushing shouldn't be done when building. Instead it should be done when a CI build passes or manually. Alternatively there can be a separate loader that does the pushing, but I won't do that with this loader for sure. You usually have very atomic loader functionality.
