### ISSUE TITLE
Generate ~/.transifexrc from environment variables

### ISSUE THREAD

**Issue by delphiactual** [freaktechnik/transifex-loader#31]
If ~/.transifexrc does not exist generate it from the environment variables:

TRANSIFEX_USER
TRANSIFEX_PASSWORD

**Comment by freaktechnik** [comment]
That's by far not enough info to generate a transifexrc. Does the official client support such a thing? Else that is IMHO not the job of this loader to do.

**Comment by delphiactual** [comment]
https://docs.transifex.com/integrations/github#integrating-the-client-with-travis-ci

Specifically step 6
```
sudo echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$TRANSIFEX_API_TOKEN"$'\n' > ~/.transifexrc
```

**Comment by freaktechnik** [comment]
Right, so as I expected, not a thing the actual client does but a way to set up the env on Travis CI in its setup scripts. Closing.
